// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm exec projen".
import type { FileProvisioner, ITerraformDependable, ITerraformIterator, LocalExecProvisioner, RemoteExecProvisioner, SSHProvisionerConnection, TerraformCount, TerraformProvider, TerraformResourceLifecycle, WinrmProvisionerConnection } from 'cdktf';

/**
 * Config for Target Group Attachment without loadBalancerArn
 */
export interface LbTargetGroupAttachmentConfig {
  /**
   * Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the [provider configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/6.25.0/docs/resources/lb_target_group_attachment#region LbTargetGroupAttachment#region}
   * @stability stable
   */
  readonly region?: string;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/6.25.0/docs/resources/lb_target_group_attachment#port LbTargetGroupAttachment#port}.
   * @stability stable
   */
  readonly port?: number;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/6.25.0/docs/resources/lb_target_group_attachment#id LbTargetGroupAttachment#id}.
   * Please be aware that the id field is automatically added to all resources in Terraform providers using a Terraform provider SDK version below 2.
   * If you experience problems setting this value it might not be settable. Please take a look at the provider documentation to ensure it should be settable.
   * @stability stable
   */
  readonly id?: string;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/6.25.0/docs/resources/lb_target_group_attachment#availability_zone LbTargetGroupAttachment#availability_zone}.
   * @stability stable
   */
  readonly availabilityZone?: string;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/6.25.0/docs/resources/lb_target_group_attachment#target_id LbTargetGroupAttachment#target_id}.
   * @stability stable
   */
  readonly targetId: string;
  /**
   * @stability experimental
   */
  readonly provisioners?: Array<FileProvisioner | LocalExecProvisioner | RemoteExecProvisioner>;
  /**
   * @stability experimental
   */
  readonly provider?: TerraformProvider;
  /**
   * @stability experimental
   */
  readonly lifecycle?: TerraformResourceLifecycle;
  /**
   * @stability experimental
   */
  readonly forEach?: ITerraformIterator;
  /**
   * @stability experimental
   */
  readonly dependsOn?: Array<ITerraformDependable>;
  /**
   * @stability experimental
   */
  readonly count?: number | TerraformCount;
  /**
   * @stability experimental
   */
  readonly connection?: SSHProvisionerConnection | WinrmProvisionerConnection;
}
