// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm exec projen".
import type { IResolvable } from 'cdktf';
import type { s3BucketLifecycleConfiguration } from '@cdktf/provider-aws';

/**
 * S3 bucket [lifecycle configuration](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lifecycle-mgmt.html) rules.
 */
export interface LifecycleConfigurationRule {
  /**
   * transition block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/6.25.0/docs/resources/s3_bucket_lifecycle_configuration#transition S3BucketLifecycleConfiguration#transition}
   * @stability stable
   */
  readonly transition?: IResolvable | Array<s3BucketLifecycleConfiguration.S3BucketLifecycleConfigurationRuleTransition>;
  /**
   * noncurrent_version_transition block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/6.25.0/docs/resources/s3_bucket_lifecycle_configuration#noncurrent_version_transition S3BucketLifecycleConfiguration#noncurrent_version_transition}
   * @stability stable
   */
  readonly noncurrentVersionTransition?: IResolvable | Array<s3BucketLifecycleConfiguration.S3BucketLifecycleConfigurationRuleNoncurrentVersionTransition>;
  /**
   * noncurrent_version_expiration block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/6.25.0/docs/resources/s3_bucket_lifecycle_configuration#noncurrent_version_expiration S3BucketLifecycleConfiguration#noncurrent_version_expiration}
   * @stability stable
   */
  readonly noncurrentVersionExpiration?: IResolvable | Array<s3BucketLifecycleConfiguration.S3BucketLifecycleConfigurationRuleNoncurrentVersionExpiration>;
  /**
   * filter block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/6.25.0/docs/resources/s3_bucket_lifecycle_configuration#filter S3BucketLifecycleConfiguration#filter}
   * @stability stable
   */
  readonly filter?: IResolvable | Array<s3BucketLifecycleConfiguration.S3BucketLifecycleConfigurationRuleFilter>;
  /**
   * expiration block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/6.25.0/docs/resources/s3_bucket_lifecycle_configuration#expiration S3BucketLifecycleConfiguration#expiration}
   * @stability stable
   */
  readonly expiration?: IResolvable | Array<s3BucketLifecycleConfiguration.S3BucketLifecycleConfigurationRuleExpiration>;
  /**
   * abort_incomplete_multipart_upload block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/6.25.0/docs/resources/s3_bucket_lifecycle_configuration#abort_incomplete_multipart_upload S3BucketLifecycleConfiguration#abort_incomplete_multipart_upload}
   * @stability stable
   */
  readonly abortIncompleteMultipartUpload?: IResolvable | Array<s3BucketLifecycleConfiguration.S3BucketLifecycleConfigurationRuleAbortIncompleteMultipartUpload>;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/6.25.0/docs/resources/s3_bucket_lifecycle_configuration#id S3BucketLifecycleConfiguration#id}.
   * Please be aware that the id field is automatically added to all resources in Terraform providers using a Terraform provider SDK version below 2.
   * If you experience problems setting this value it might not be settable. Please take a look at the provider documentation to ensure it should be settable.
   * @stability stable
   */
  readonly id: string;
  /**
   * Specifies the lifecycle rule status.
   * @default `true`
   */
  readonly enabled?: boolean;
}
