// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm exec projen".
import type { IResolvable } from 'cdktf';
import type { securityGroup } from '@cdktf/provider-aws';

/**
 * Config for network connectivity to AWS resources in a VPC, specify a list
 * of security groups and subnets in the VPC.
 * When you connect a function to a VPC, it can only access resources and the internet through that VPC.
 *
 * See [VPC Settings](https://docs.aws.amazon.com/lambda/latest/dg/configuration-vpc.html).
 */
export interface VpcConfig {
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/6.25.0/docs/resources/lambda_function#ipv6_allowed_for_dual_stack LambdaFunction#ipv6_allowed_for_dual_stack}.
   * @stability stable
   */
  readonly ipv6AllowedForDualStack?: boolean | IResolvable;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/6.25.0/docs/resources/lambda_function#subnet_ids LambdaFunction#subnet_ids}.
   * @stability stable
   */
  readonly subnetIds: Array<string>;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/6.25.0/docs/resources/lambda_function#security_group_ids LambdaFunction#security_group_ids}.
   * @default created
   * @stability stable
   */
  readonly securityGroupIds?: Array<string>;
  /**
   * Egress rules, used for created securityGroup if `securityGroupIds` are not provided
   * @default egress world
   */
  readonly egress?: Array<securityGroup.SecurityGroupEgress>;
  /**
   * The VPC ID, required if `securityGroupIds` are not provided
   */
  readonly vpcId?: string;
}
